baseURL = 'https://AceN34.github.io/hugo_ejemplo/'
languageCode = 'en-us'
title = 'Web de Jorge'
canonifyURLs = true

theme = "relearn"

[[params.themeVariant]]
    identifier = 'neon'

[[params.themeVariant]]
    identifier = 'learn'

[[params.themeVariant]]
    identifier = 'blue'
